.cargo/config, src/ephemeris.rs
Fixes a compilation issue on Windows and adds a stack size linker flag which is necessary to run the tests (sadly, this flag is also needed if you are linking against `swiftnav-rs` on windows).
=> windows support

src/ephemeris.rs, src/signal.rs, src/solver.rs
This changes our rust enums to no longer attempt to directly mirror the C enums. The C representation can change based on target system, and we risk invoking undefined behavior if a new value or undefined value comes from the C code and we attempt to convert into the Rust enum. Instead conversion functions have been added where necessary. All of the the C->Rust conversions were already implemented and were double checking the values and returning a Option in case an invalid value was received.
=> Clean up enum representations

Cargo.toml, README.md
Update the cargo version to `0.2.0` and make the README a bit more clear. Will manually tag v0.2.0 after this is merged.
=> New release changes

build.rs, src/c_bindings.rs, src/ephemeris.rs, src/ionosphere.rs, src/navmeas.rs, src/signal.rs, src/solver.rs
Address several usability issues I ran into while trying to use this crate over the weekend. These changes can be summed up as:
* Add several getter functions
* Expand the use of default derived traits as much as possible
* Remove use of borrows of `GpsTime`, which is copyable by default
* Fix misc compiler warnings to make use of the crate cleaner
=> Usability additions

Cargo.toml, Jenkinsfile, src/ephemeris.rs, src/navmeas.rs, src/signal.rs, src/time.rs
Added implementations of `TryFrom` for converting message types from libsbp into various types. These definitions are behind a feature flag. The following conversions are included:
- `MsgEphemerisGPS` -> `Ephemeris`
- `MsgEphemerisGal` -> `Ephemeris`
- `MsgObs` -> `Vec<NavigationMeasurement>`
- `u8` -> `Code`
- (SBP) `GnssSignal` -> `GnssSignal`
- (SBP) `GPSTime` -> `GpsTime`
- `GPSTimeSec` -> `GpsTime`
The ephemeris conversion contains conversions of `GnssSignal` and `GpsTime` so has a new error type to signal these compound error cases.
=> Added functions for constructing objects from SBP messages

build.rs
Second part of a two part fix for https://swift-nav.atlassian.net/browse/INFRA-477 -- similar to other -sys crates such as https://github.com/google/shaderc-rs/blob/master/shaderc-sys/build/build.rs -- set the CMAKE_INSTALL_PREFIX to the compile dir so that we don't need root access to run the install target.
=> build.rs: set CMAKE_INSTALL_PREFIX

Cargo.toml, build.rs
Allows reducing build time by ~1/3
=> Create default feature testcpp for C++ tests

README.md, src/c_bindings.rs, src/coords.rs, src/edc.rs, src/ephemeris.rs, src/ionosphere.rs, src/lib.rs, src/navmeas.rs, src/signal.rs, src/solver.rs, src/troposphere.rs
Cleaned up the formatting and spelling in the README. Also added some more introductory information to the crate docs. `swiftnav-rs` is never going to be a "plug and play" positioning library, but I felt like it could do with a little bit of a prelude explaining what functionality it provides and the type of developer that might be interested in using it.
=> Add introductory documentation

src/coords.rs, src/ephemeris.rs, src/navmeas.rs, src/signal.rs, src/solver.rs
As mentioned in https://github.com/swift-nav/swiftnav-rs/pull/63#discussion_r680417714 we have several inconsistencies in the function naming style and a few clippy warnings to clean up.
- Remove `get_` prefix on getter functions
- Clean up some pattern matching logic per `clippy` advice
- Make `to_` conversion functions consume `self` to match common convention
=> Update code to be more inline with the Rust API style

Cargo.toml, build.rs
While we should probably be running the C/C++ tests in the CI for this crate, I don't think it makes much sense to be running them by default in other crates that use this. Our CI should be building with `--all-features` already so the tests will be built and run.
=> Remove cpp tests from the default features.

swiftnav-sys/build.rs
On CentOS libswiftnav installs into `lib64` -- so add `lib64` as a directory that we search for the library.
---
Tested on a CentOS 7 VM.  Installed clang 9 from here:
- https://releases.llvm.org/download.html#9.0.0 (`SuSE Linux Enterprise Server 11SP3 x86_64` variant)
CMake from pre-built binary: https://cmake.org/download/
Rust and cargo from https://rustup.rs
=> swiftnav-sys: fixes compatibility with CentOS

swiftnav/Cargo.toml, swiftnav/src/coords.rs, swiftnav/src/ionosphere.rs, swiftnav/src/time.rs
- Rename `chrono-support` feature to `chrono`
- Escapes some braces in doc comments/fixes a few links
=> crates.io release cleanup

.github/workflows/ci.yaml
While building #76 I ran into issues with the Windows build hanging. It looks like LLVM is now installed by default, so we don't need to manually install it anymore.
Problematic build: https://github.com/swift-nav/swiftnav-rs/runs/3804887134?check_suite_focus=true#step:5:26
=> Remove step to manually install LLVM on windows

swiftnav-sys/build.rs, swiftnav/src/time.rs
With the latest update to `libswiftnav` a function to convert UTC times into GPS has been added. This exposes this functionality in the Rust wrapper.
=> Add wrappers for converting UTC times into GPS times

.github/workflows/ci.yaml, Makefile.toml, swiftnav-sys/Cargo.toml, swiftnav/Cargo.toml, swiftnav/src/time.rs
Add a `total_cmp` method similar to the `f64::total_cmp` introduced in Rust 1.62 -- this should simplify operations that require sorting `GpsTime` values (and other related operations that require a total order).
=> Add total_cmp function 

swiftnav/src/time.rs
Seems like a patch update to the chrono crate included a breaking change to the API which caused our build to break. This PR fixes that in a quick way.
=> Fix compile errors from chrono

.github/workflows/ci.yaml, swiftnav/src/solver.rs
Seems like a recent update to Rust meant the `MAX` constant we were using moved and clippy started telling us to use the new preferred associated constant. This fixes that new clippy failure, and also updates the CI action to run on a weekly basis, hopefully that'll mean we catch these lint failures earlier and fix them before unrelated PRs get blocked by them.
=> Fix an errant clippy warning

swiftnav/Cargo.toml, swiftnav/src/coords.rs, swiftnav/src/lib.rs, swiftnav/src/reference_frame.rs, swiftnav/src/time.rs, swiftnav/tests/reference_frames.rs
This adds common functionality related to reference frame conversion.
* Adds some basic operations to help ease the use of the `ECEF` type, which gets mathematically manipulated in the reference frame transformations
* Adds a helper function to get the fractional year representation of a point in time, which is helpful in the reference frame transformations
* Adds a new `Coordinate` type which aggregates together position, velocity, time, and reference frame.
* Adds a new `Transformation` type which contains the needed information to transform between two reference frames, and can transform a `Coordinate` object
=> Reference frame basics

.github/dependabot.yml
Also have Dependabot tag the open-source team to review dependency updates. Also also drop the frequency to once a week.
=> Update Dependabot to also check for github action updates

swiftnav/src/reference_frame/mod.rs
We've discussed adding this, and now I've had a real need to do this. This is the MVP implementation for helping find the "shortest path" series of transformations. This is accomplished by building up a graph  with the reference frames as vertices and the transformations as edges, then performing a breadth-first search through this graph for the first available path.
I've implemented this functionality as an additional function to avoid breaking API changes. In a future revision I would like to roll up this functionality into the `get_transformation()` function and make it transparent, but doing that in the way I am thinking would require adding a new type representing a compound transformation and modifying the `Transformation` struct to be able to use it.
=> Add a helper type for finding multi-step reference frame transformations

swiftnav/src/reference_frame/mod.rs, swiftnav/src/reference_frame/params.rs
Add a few WGS84 realizations to the list of supported reference frames. These realizations are simple enough to add since they are aligned to specific ITRF realizations at specific epochs, so the transformation parameters between WGS84 and ITRF are all zero.
=> Add the last few realizations of WGS84

.github/workflows/ci.yaml
Seems like we finally got hit by the rustup v1.28 changes (Github action runners likely updated between last week and now). We were previously using [actions-rs/toolchain](https://github.com/actions-rs/toolchain) but that has been archived for a while. Instead I've simply replaced that action with a couple of manual `rustup` commands.
=> Fix Rustup step in CI

katex-header.html, swiftnav/Cargo.toml, swiftnav/src/coords.rs, swiftnav/src/edc.rs, swiftnav/src/reference_frame/mod.rs
There are a few places where a bit of LaTeX would help make things a bit more clear in our documentation. Indeed the C library documentation has several uses of LaTeX which Doxygen handles. This is based on the [rustdoc-katex-demo](https://github.com/paulkernfeld/rustdoc-katex-demo) crate, which demonstates how to include a link to the KaTex code in the HTML generated for the documents.
The coord documentation has been changed from this
to
And the helmert transformation docs is now hopefully a bit more clear with the transformation formula fully displayed
=> Add LaTeX formatting to doc comments

.env, .github/workflows/ci.yaml, justfile, swiftnav-sys/src/lib.rs
We've got a couple of non-trivial commands to build docs with the proper katex headers. So why not add a `justfile` to help simplify common operations?
=> Add a justfile

swiftnav/README.md, swiftnav/src/coords/ecef.rs, swiftnav/src/coords/llh.rs, swiftnav/src/coords/mod.rs, swiftnav/src/coords/ned.rs
Think I got a little over zealous with the RIIR, and removed a couple of nice to have functions.
Is it acceptable to have multiple `AsRef` impls on a type? It seems like the stdlin does (e.g. `Vec` implements two different `AsRef`). Also is it preferable to not have dedicated functions and only rely on the `AsRef` impl for casting?
=> Add nice to have functions for coordindate types

.github/workflows/ci.yaml
Master build [failed earlier](https://github.com/swift-nav/swiftnav-rs/actions/runs/17739419661), seems like the Github runners updated their CMake to a version that deprecates support for the minimum version used in the C library build.
We're in the middle of a refactor to remove the dependency on the C library, but to unblock further builds I've added an environment variable to work around the CMake build failure.
=> Set an environment variable to unblock cmake build for now
